config/routes.rb
Rails.application.routes.draw do
  resources :money_savings
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Defines the root path route ("/")
  # root "articles#index"
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/money_saving.rb
class MoneySaving < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/money_savings_controller.rb
class MoneySavingsController < ApplicationController
  before_action :set_money_saving, only: %i[ show edit update destroy ]

  # GET /money_savings or /money_savings.json
  def index
    @money_savings = MoneySaving.all
  end

  # GET /money_savings/1 or /money_savings/1.json
  def show
  end

  # GET /money_savings/new
  def new
    @money_saving = MoneySaving.new
  end

  # GET /money_savings/1/edit
  def edit
  end

  # POST /money_savings or /money_savings.json
  def create
    @money_saving = MoneySaving.new(money_saving_params)

    respond_to do |format|
      if @money_saving.save
        format.html { redirect_to money_saving_url(@money_saving), notice: "Money saving was successfully created." }
        format.json { render :show, status: :created, location: @money_saving }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @money_saving.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /money_savings/1 or /money_savings/1.json
  def update
    respond_to do |format|
      if @money_saving.update(money_saving_params)
        format.html { redirect_to money_saving_url(@money_saving), notice: "Money saving was successfully updated." }
        format.json { render :show, status: :ok, location: @money_saving }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @money_saving.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /money_savings/1 or /money_savings/1.json
  def destroy
    @money_saving.destroy

    respond_to do |format|
      format.html { redirect_to money_savings_url, notice: "Money saving was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_money_saving
      @money_saving = MoneySaving.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def money_saving_params
      params.require(:money_saving).permit(:saving_date, :amount, :saving_amount)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/money_savings_helper.rb
module MoneySavingsHelper
end

app/views/home/index.html.erb
<div>
  <%= link_to 'money savings', money_savings_path %>
</div>
<div>
  <%= button_to 'sign_out', destroy_user_session_path, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SavingMoney</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/money_savings/_form.html.erb
<%= form_with(model: money_saving, class: "contents") do |form| %>
  <% if money_saving.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(money_saving.errors.count, "error") %> prohibited this money_saving from being saved:</h2>

      <ul>
        <% money_saving.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :saving_date %>
    <%= form.date_field :saving_date, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :amount %>
    <%= form.text_field :amount, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :saving_amount %>
    <%= form.text_field :saving_amount, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/money_savings/_money_saving.html.erb
<div id="<%= dom_id money_saving %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Saving date:</strong>
    <%= money_saving.saving_date %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Amount:</strong>
    <%= money_saving.amount %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Saving amount:</strong>
    <%= money_saving.saving_amount %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this money saving", money_saving, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this money saving', edit_money_saving_path(money_saving), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/money_savings/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing money saving</h1>

  <%= render "form", money_saving: @money_saving %>

  <%= link_to "Show this money saving", @money_saving, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to money savings", money_savings_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/money_savings/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Money savings</h1>
    <%= link_to 'New money saving', new_money_saving_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="money_savings" class="min-w-full">
    <%= render @money_savings %>
  </div>
</div>

app/views/money_savings/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New money saving</h1>

  <%= render "form", money_saving: @money_saving %>

  <%= link_to 'Back to money savings', money_savings_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/money_savings/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @money_saving %>

    <%= link_to 'Edit this money_saving', edit_money_saving_path(@money_saving), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this money_saving', money_saving_path(@money_saving), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to money_savings', money_savings_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>